#define BOOLEAN 1
#define BREAK 2
#define CLASS 3
#define DOUBLE 4
#define ELSE 5
#define EXTENDS 6
#define FOR 7
#define IF 8
#define IMPLEMENTS 9
#define INT 10
#define INTERFACE 11
#define NEWARRAY 12
#define PRINTLN 13
#define READLN 14
#define RETURN 15
#define STRING 16
#define VOID 17
#define WHILE 18
#define PLUS 19
#define MINUS 20
#define MULTIPLICATION 21
#define DIVISION 22
#define MOD 23
#define LESS 24
#define LESSEQUAL 25
#define GREATER 26
#define GREATEREQUAL 27
#define EQUAL 28
#define NOTEQUAL 29
#define AND 30
#define OR 31
#define NOT 32
#define ASSIGNOP 33
#define SEMICOLON 34
#define COMMA 35
#define PERIOD 36
#define LEFTPAREN 37
#define RIGHTPAREN 38
#define LEFTBRACKET 39
#define RIGHTBRACKET 40
#define LEFTBRACE 41
#define RIGHTBRACE 42
#define INTCONSTANT 43
#define DOUBLECONSTANT 44
#define STRINGCONSTANT 45
#define BOOLEANCONSTANT 46
#define ID 47
